### ISSUE TITLE
PKGBUILD for AUR "make -jN"

### ISSUE THREAD

**Issue by conrad784** [BorgwardtLab/S3M#3]
concerning [the PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=s3m-git)

makepkg accepts MAKEFLAGS in `/etc/makepkg.conf` [makepkg](https://wiki.archlinux.org/index.php/makepkg#Parallel_compilation)
setting `-j8` per default is therefore unwanted and might lead to unexpected results

**Comment by Submanifold** [comment]
Thank you for reporting this! I will update the PKGBUILD accordingly.

**Comment by Submanifold** [comment]
Fixed! Could you please retest?
