### ISSUE TITLE
Can this package be conducted in R

### ISSUE THREAD

**Issue by zh-zhang1984** [BorgwardtLab/S3M#4]
I am R user and found this algorithm really helpful for my current project. So I want to know if this can be performed in R?

**Comment by Pseudomanifold** [comment]
Sorry, but at this point, we have no R implementation available. It should be possible to call the command-line tool from R, though. See the [`system2`](https://stat.ethz.ch/R-manual/R-devel/library/base/html/system2.html) command for more information.
